In [2]:
import numpy as np

us_data_path = "./us_data.csv"
gk_data_path = "./gk_data.csv"

###加载数据
_us_data = np.loadtxt(us_data_path,delimiter=",",dtype=int)
_gk_data = np.loadtxt(gk_data_path,delimiter=",",dtype=int)


array([[1232, 1111,   13,    1],
       [4332, 1314,   32,    1],
       [1311,  234,   11,    5],
       [ 432,  232,   22,    2]])

In [3]:
_us_data

array([[ 1213,   136,    23,     1],
       [ 1131,  1111,   232,     0],
       [11424,  8731,  2324,  1213],
       [  434,   234,    12,    54]])

In [4]:
_gk_data

array([[1232, 1111,   13,    1],
       [4332, 1314,   32,    1],
       [1311,  234,   11,    5],
       [ 432,  232,   22,    2]])

In [5]:
zeros_data = np.zeros((_us_data.shape[0],1)).astype(int)
zeros_data

array([[0],
       [0],
       [0],
       [0]])

In [6]:
ones_data = np.ones((_gk_data.shape[0],1)).astype(int)

In [7]:
###数据的拼接
us_data = np.hstack((_us_data,zeros_data))
gk_data = np.hstack((_gk_data,ones_data))

In [9]:
data = np.vstack((us_data,gk_data))
data

array([[ 1213,   136,    23,     1,     0],
       [ 1131,  1111,   232,     0,     0],
       [11424,  8731,  2324,  1213,     0],
       [  434,   234,    12,    54,     0],
       [ 1232,  1111,    13,     1,     1],
       [ 4332,  1314,    32,     1,     1],
       [ 1311,   234,    11,     5,     1],
       [  432,   232,    22,     2,     1]])